server:
  port: 9000
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///loginuser

  data:
    redis:
      port: 6379
      host: localhost
logging:
  level:
    com.dsdaaa: debug
